export interface DSVariable {
  name: string;
  type: 'COLOR' | 'FLOAT' | 'STRING';
  values: Record<string, string | number>;
}

export interface DSCollection {
  name: string;
  modes: Record<string, string>;
  variables: DSVariable[];
}

export const DESIGN_SYSTEM_COLLECTIONS: DSCollection[] = [
  {
    name: 'Brand',
    modes: { '0': 'Mode 1' },
    variables: [
      { name: 'Foundation/Black', type: 'COLOR', values: { '0': '#000000' } },
      { name: 'Foundation/White', type: 'COLOR', values: { '0': '#ffffff' } },
      { name: 'Grey/10', type: 'COLOR', values: { '0': '#fcfcfd' } },
      { name: 'Grey/50', type: 'COLOR', values: { '0': '#f5f7f9' } },
      { name: 'Grey/60', type: 'COLOR', values: { '0': '#f5f7f9' } },
      { name: 'Grey/75', type: 'COLOR', values: { '0': '#eef0f5' } },
      { name: 'Grey/100', type: 'COLOR', values: { '0': '#dde2eb' } },
      { name: 'Grey/200', type: 'COLOR', values: { '0': '#c5cddd' } },
      { name: 'Grey/300', type: 'COLOR', values: { '0': '#aeb9cf' } },
      { name: 'Grey/400', type: 'COLOR', values: { '0': '#96a4c1' } },
      { name: 'Grey/500', type: 'COLOR', values: { '0': '#7e8fb3' } },
      { name: 'Grey/600', type: 'COLOR', values: { '0': '#6a7896' } },
      { name: 'Grey/700', type: 'COLOR', values: { '0': '#57617a' } },
      { name: 'Grey/800', type: 'COLOR', values: { '0': '#434b5d' } },
      { name: 'Grey/900', type: 'COLOR', values: { '0': '#303441' } },
      { name: 'Grey/950', type: 'COLOR', values: { '0': '#262932' } },
      { name: 'Blue/10', type: 'COLOR', values: { '0': '#fafcff' } },
      { name: 'Blue/50', type: 'COLOR', values: { '0': '#eef4ff' } },
      { name: 'Blue/100', type: 'COLOR', values: { '0': '#dce4fd' } },
      { name: 'Blue/200', type: 'COLOR', values: { '0': '#b9c7fb' } },
      { name: 'Blue/300', type: 'COLOR', values: { '0': '#96acf9' } },
      { name: 'Blue/400', type: 'COLOR', values: { '0': '#7491f7' } },
      { name: 'Blue/500', type: 'COLOR', values: { '0': '#3d64ed' } },
      { name: 'Blue/600', type: 'COLOR', values: { '0': '#3456d0' } },
      { name: 'Blue/700', type: 'COLOR', values: { '0': '#324cab' } },
      { name: 'Blue/800', type: 'COLOR', values: { '0': '#304287' } },
      { name: 'Blue/900', type: 'COLOR', values: { '0': '#2e3862' } },
      { name: 'Blue/950', type: 'COLOR', values: { '0': '#1d2443' } },
      { name: 'Orange/10', type: 'COLOR', values: { '0': '#fffbfa' } },
      { name: 'Orange/50', type: 'COLOR', values: { '0': '#fff2ed' } },
      { name: 'Orange/100', type: 'COLOR', values: { '0': '#ffdfd4' } },
      { name: 'Orange/200', type: 'COLOR', values: { '0': '#ffbea8' } },
      { name: 'Orange/300', type: 'COLOR', values: { '0': '#ff9271' } },
      { name: 'Orange/400', type: 'COLOR', values: { '0': '#ff6136' } },
      { name: 'Orange/500', type: 'COLOR', values: { '0': '#fa420f' } },
      { name: 'Orange/600', type: 'COLOR', values: { '0': '#dd370e' } },
      { name: 'Orange/700', type: 'COLOR', values: { '0': '#c62e08' } },
      { name: 'Orange/800', type: 'COLOR', values: { '0': '#9d2b0f' } },
      { name: 'Orange/900', type: 'COLOR', values: { '0': '#7e2210' } },
      { name: 'Orange/950', type: 'COLOR', values: { '0': '#4a170c' } },
      { name: 'Green/10', type: 'COLOR', values: { '0': '#fbfefd' } },
      { name: 'Green/50', type: 'COLOR', values: { '0': '#f2fbf9' } },
      { name: 'Green/100', type: 'COLOR', values: { '0': '#d2f5ee' } },
      { name: 'Green/200', type: 'COLOR', values: { '0': '#a6e9de' } },
      { name: 'Green/300', type: 'COLOR', values: { '0': '#64d3c5' } },
      { name: 'Green/400', type: 'COLOR', values: { '0': '#44bdb2' } },
      { name: 'Green/500', type: 'COLOR', values: { '0': '#2ba198' } },
      { name: 'Green/600', type: 'COLOR', values: { '0': '#20817c' } },
      { name: 'Green/700', type: 'COLOR', values: { '0': '#1d6864' } },
      { name: 'Green/800', type: 'COLOR', values: { '0': '#1c5352' } },
      { name: 'Green/900', type: 'COLOR', values: { '0': '#1b4644' } },
      { name: 'Green/950', type: 'COLOR', values: { '0': '#0f2928' } },
      { name: 'Red/10', type: 'COLOR', values: { '0': '#fffafa' } },
      { name: 'Red/50', type: 'COLOR', values: { '0': '#fff0f0' } },
      { name: 'Red/100', type: 'COLOR', values: { '0': '#ffe2e4' } },
      { name: 'Red/200', type: 'COLOR', values: { '0': '#ffcace' } },
      { name: 'Red/300', type: 'COLOR', values: { '0': '#ff9fa6' } },
      { name: 'Red/400', type: 'COLOR', values: { '0': '#ff6977' } },
      { name: 'Red/500', type: 'COLOR', values: { '0': '#ff485e' } },
      { name: 'Red/600', type: 'COLOR', values: { '0': '#ed1136' } },
      { name: 'Red/700', type: 'COLOR', values: { '0': '#c8082d' } },
      { name: 'Red/800', type: 'COLOR', values: { '0': '#a8092d' } },
      { name: 'Red/900', type: 'COLOR', values: { '0': '#8f0c2d' } },
      { name: 'Red/950', type: 'COLOR', values: { '0': '#570c1f' } },
      { name: 'Yellow/10', type: 'COLOR', values: { '0': '#fffefa' } },
      { name: 'Yellow/50', type: 'COLOR', values: { '0': '#fffaed' } },
      { name: 'Yellow/100', type: 'COLOR', values: { '0': '#fff4d5' } },
      { name: 'Yellow/200', type: 'COLOR', values: { '0': '#ffe5a9' } },
      { name: 'Yellow/300', type: 'COLOR', values: { '0': '#fed173' } },
      { name: 'Yellow/400', type: 'COLOR', values: { '0': '#fdb23a' } },
      { name: 'Yellow/500', type: 'COLOR', values: { '0': '#fb9814' } },
      { name: 'Yellow/600', type: 'COLOR', values: { '0': '#f5810b' } },
      { name: 'Yellow/700', type: 'COLOR', values: { '0': '#c45e0a' } },
      { name: 'Yellow/800', type: 'COLOR', values: { '0': '#9b4911' } },
      { name: 'Yellow/900', type: 'COLOR', values: { '0': '#7d3d11' } },
      { name: 'Yellow/950', type: 'COLOR', values: { '0': '#4d260c' } },
      { name: 'Purple/10', type: 'COLOR', values: { '0': '#fbfaff' } },
      { name: 'Purple/50', type: 'COLOR', values: { '0': '#f4f0ff' } },
      { name: 'Purple/100', type: 'COLOR', values: { '0': '#e8e2fe' } },
      { name: 'Purple/200', type: 'COLOR', values: { '0': '#e0d5ff' } },
      { name: 'Purple/300', type: 'COLOR', values: { '0': '#c8b4fe' } },
      { name: 'Purple/400', type: 'COLOR', values: { '0': '#a278fb' } },
      { name: 'Purple/500', type: 'COLOR', values: { '0': '#8e4ef9' } },
      { name: 'Purple/600', type: 'COLOR', values: { '0': '#802ced' } },
      { name: 'Purple/700', type: 'COLOR', values: { '0': '#691fc1' } },
      { name: 'Purple/800', type: 'COLOR', values: { '0': '#601daf' } },
      { name: 'Purple/900', type: 'COLOR', values: { '0': '#4d198a' } },
      { name: 'Purple/950', type: 'COLOR', values: { '0': '#2a0f4a' } },
      { name: 'Scale/0', type: 'FLOAT', values: { '0': 0 } },
      { name: 'Scale/1', type: 'FLOAT', values: { '0': 1 } },
      { name: 'Scale/2', type: 'FLOAT', values: { '0': 2 } },
      { name: 'Scale/4', type: 'FLOAT', values: { '0': 4 } },
      { name: 'Scale/6', type: 'FLOAT', values: { '0': 6 } },
      { name: 'Scale/8', type: 'FLOAT', values: { '0': 8 } },
      { name: 'Scale/12', type: 'FLOAT', values: { '0': 12 } },
      { name: 'Scale/16', type: 'FLOAT', values: { '0': 16 } },
      { name: 'Scale/20', type: 'FLOAT', values: { '0': 20 } },
      { name: 'Scale/24', type: 'FLOAT', values: { '0': 24 } },
      { name: 'Scale/28', type: 'FLOAT', values: { '0': 28 } },
      { name: 'Scale/32', type: 'FLOAT', values: { '0': 32 } },
      { name: 'Scale/100', type: 'FLOAT', values: { '0': 100 } },
      { name: 'Opacity/50', type: 'FLOAT', values: { '0': 50 } },
      { name: 'Font Family/Headings', type: 'STRING', values: { '0': 'Inter' } },
      { name: 'Font Family/Body', type: 'STRING', values: { '0': 'Inter' } },
      { name: 'Font Weight/Regular', type: 'STRING', values: { '0': 'Regular' } },
      { name: 'Font Weight/Medium', type: 'STRING', values: { '0': 'Medium' } },
      { name: 'Font Weight/Semi Bold', type: 'STRING', values: { '0': 'Semi Bold' } },
      { name: 'Font Weight/Bold', type: 'STRING', values: { '0': 'Bold' } },
    ],
  },
  {
    name: 'Alias',
    modes: { '0': 'Mode 1' },
    variables: [
      { name: 'Primary/10', type: 'COLOR', values: { '0': 'Blue/10' } },
      { name: 'Primary/50', type: 'COLOR', values: { '0': 'Blue/50' } },
      { name: 'Primary/100', type: 'COLOR', values: { '0': 'Blue/100' } },
      { name: 'Primary/200', type: 'COLOR', values: { '0': 'Blue/200' } },
      { name: 'Primary/300', type: 'COLOR', values: { '0': 'Blue/300' } },
      { name: 'Primary/400', type: 'COLOR', values: { '0': 'Blue/400' } },
      { name: 'Primary/Default', type: 'COLOR', values: { '0': 'Blue/500' } },
      { name: 'Primary/600', type: 'COLOR', values: { '0': 'Blue/600' } },
      { name: 'Primary/700', type: 'COLOR', values: { '0': 'Blue/700' } },
      { name: 'Primary/800', type: 'COLOR', values: { '0': 'Blue/800' } },
      { name: 'Primary/900', type: 'COLOR', values: { '0': 'Blue/900' } },
      { name: 'Primary/950', type: 'COLOR', values: { '0': 'Blue/950' } },
      { name: 'Accent/10', type: 'COLOR', values: { '0': 'Orange/10' } },
      { name: 'Accent/50', type: 'COLOR', values: { '0': 'Orange/50' } },
      { name: 'Accent/100', type: 'COLOR', values: { '0': 'Orange/100' } },
      { name: 'Accent/200', type: 'COLOR', values: { '0': 'Orange/200' } },
      { name: 'Accent/300', type: 'COLOR', values: { '0': 'Orange/300' } },
      { name: 'Accent/Default', type: 'COLOR', values: { '0': 'Orange/400' } },
      { name: 'Accent/500', type: 'COLOR', values: { '0': 'Orange/500' } },
      { name: 'Accent/600', type: 'COLOR', values: { '0': 'Orange/600' } },
      { name: 'Accent/700', type: 'COLOR', values: { '0': 'Orange/700' } },
      { name: 'Accent/800', type: 'COLOR', values: { '0': 'Orange/800' } },
      { name: 'Accent/900', type: 'COLOR', values: { '0': 'Orange/900' } },
      { name: 'Accent/950', type: 'COLOR', values: { '0': 'Orange/950' } },
      { name: 'Success/10', type: 'COLOR', values: { '0': 'Green/10' } },
      { name: 'Success/50', type: 'COLOR', values: { '0': 'Green/50' } },
      { name: 'Success/100', type: 'COLOR', values: { '0': 'Green/100' } },
      { name: 'Success/200', type: 'COLOR', values: { '0': 'Green/200' } },
      { name: 'Success/300', type: 'COLOR', values: { '0': 'Green/300' } },
      { name: 'Success/Default', type: 'COLOR', values: { '0': 'Green/400' } },
      { name: 'Success/500', type: 'COLOR', values: { '0': 'Green/500' } },
      { name: 'Success/600', type: 'COLOR', values: { '0': 'Green/600' } },
      { name: 'Success/700', type: 'COLOR', values: { '0': 'Green/700' } },
      { name: 'Success/800', type: 'COLOR', values: { '0': 'Green/800' } },
      { name: 'Success/900', type: 'COLOR', values: { '0': 'Green/900' } },
      { name: 'Success/950', type: 'COLOR', values: { '0': 'Green/950' } },
      { name: 'Warning/10', type: 'COLOR', values: { '0': 'Yellow/10' } },
      { name: 'Warning/50', type: 'COLOR', values: { '0': 'Yellow/50' } },
      { name: 'Warning/100', type: 'COLOR', values: { '0': 'Yellow/100' } },
      { name: 'Warning/200', type: 'COLOR', values: { '0': 'Yellow/200' } },
      { name: 'Warning/300', type: 'COLOR', values: { '0': 'Yellow/300' } },
      { name: 'Warning/400', type: 'COLOR', values: { '0': 'Yellow/400' } },
      { name: 'Warning/default', type: 'COLOR', values: { '0': 'Yellow/500' } },
      { name: 'Warning/600', type: 'COLOR', values: { '0': 'Yellow/600' } },
      { name: 'Warning/700', type: 'COLOR', values: { '0': 'Yellow/700' } },
      { name: 'Warning/800', type: 'COLOR', values: { '0': 'Yellow/800' } },
      { name: 'Warning/900', type: 'COLOR', values: { '0': 'Yellow/900' } },
      { name: 'Warning/950', type: 'COLOR', values: { '0': 'Yellow/950' } },
      { name: 'Danger/10', type: 'COLOR', values: { '0': 'Red/10' } },
      { name: 'Danger/50', type: 'COLOR', values: { '0': 'Red/50' } },
      { name: 'Danger/100', type: 'COLOR', values: { '0': 'Red/100' } },
      { name: 'Danger/200', type: 'COLOR', values: { '0': 'Red/200' } },
      { name: 'Danger/300', type: 'COLOR', values: { '0': 'Red/300' } },
      { name: 'Danger/400', type: 'COLOR', values: { '0': 'Red/400' } },
      { name: 'Danger/default', type: 'COLOR', values: { '0': 'Red/500' } },
      { name: 'Danger/600', type: 'COLOR', values: { '0': 'Red/600' } },
      { name: 'Danger/700', type: 'COLOR', values: { '0': 'Red/700' } },
      { name: 'Danger/800', type: 'COLOR', values: { '0': 'Red/800' } },
      { name: 'Danger/900', type: 'COLOR', values: { '0': 'Red/900' } },
      { name: 'Danger/950', type: 'COLOR', values: { '0': 'Red/950' } },
      { name: 'Neutral/White', type: 'COLOR', values: { '0': 'Foundation/White' } },
      { name: 'Neutral/Black', type: 'COLOR', values: { '0': 'Foundation/Black' } },
      { name: 'Neutral/10', type: 'COLOR', values: { '0': 'Grey/10' } },
      { name: 'Neutral/50', type: 'COLOR', values: { '0': 'Grey/50' } },
      { name: 'Neutral/60', type: 'COLOR', values: { '0': 'Grey/60' } },
      { name: 'Neutral/75', type: 'COLOR', values: { '0': 'Grey/75' } },
      { name: 'Neutral/100', type: 'COLOR', values: { '0': 'Grey/100' } },
      { name: 'Neutral/200', type: 'COLOR', values: { '0': 'Grey/200' } },
      { name: 'Neutral/300', type: 'COLOR', values: { '0': 'Grey/300' } },
      { name: 'Neutral/Default', type: 'COLOR', values: { '0': 'Grey/400' } },
      { name: 'Neutral/500', type: 'COLOR', values: { '0': 'Grey/500' } },
      { name: 'Neutral/600', type: 'COLOR', values: { '0': 'Grey/600' } },
      { name: 'Neutral/700', type: 'COLOR', values: { '0': 'Grey/700' } },
      { name: 'Neutral/800', type: 'COLOR', values: { '0': 'Grey/800' } },
      { name: 'Neutral/900', type: 'COLOR', values: { '0': 'Grey/900' } },
      { name: 'Neutral/950', type: 'COLOR', values: { '0': 'Grey/950' } },
      { name: 'Information/10', type: 'COLOR', values: { '0': 'Blue/10' } },
      { name: 'Information/50', type: 'COLOR', values: { '0': 'Blue/50' } },
      { name: 'Information/100', type: 'COLOR', values: { '0': 'Blue/100' } },
      { name: 'Information/200', type: 'COLOR', values: { '0': 'Blue/200' } },
      { name: 'Information/300', type: 'COLOR', values: { '0': 'Blue/300' } },
      { name: 'Information/400', type: 'COLOR', values: { '0': 'Blue/400' } },
      { name: 'Information/500', type: 'COLOR', values: { '0': 'Blue/500' } },
      { name: 'Information/Default', type: 'COLOR', values: { '0': 'Blue/600' } },
      { name: 'Information/700', type: 'COLOR', values: { '0': 'Blue/700' } },
      { name: 'Information/800', type: 'COLOR', values: { '0': 'Blue/800' } },
      { name: 'Information/900', type: 'COLOR', values: { '0': 'Blue/900' } },
      { name: 'Information/950', type: 'COLOR', values: { '0': 'Blue/950' } },
      { name: 'AI/10', type: 'COLOR', values: { '0': 'Purple/10' } },
      { name: 'AI/50', type: 'COLOR', values: { '0': 'Purple/50' } },
      { name: 'AI/75', type: 'COLOR', values: { '0': 'Purple/100' } },
      { name: 'AI/100', type: 'COLOR', values: { '0': 'Purple/200' } },
      { name: 'AI/200', type: 'COLOR', values: { '0': 'Purple/300' } },
      { name: 'AI/300', type: 'COLOR', values: { '0': 'Purple/400' } },
      { name: 'AI/Default', type: 'COLOR', values: { '0': 'Purple/500' } },
      { name: 'AI/500', type: 'COLOR', values: { '0': 'Purple/600' } },
      { name: 'AI/600', type: 'COLOR', values: { '0': 'Purple/700' } },
      { name: 'AI/700', type: 'COLOR', values: { '0': 'Purple/800' } },
      { name: 'AI/800', type: 'COLOR', values: { '0': 'Purple/900' } },
      { name: 'AI/900', type: 'COLOR', values: { '0': 'Purple/950' } },
      { name: 'Border Width/none', type: 'FLOAT', values: { '0': 'Scale/0' } },
      { name: 'Border Width/sm', type: 'FLOAT', values: { '0': 'Scale/1' } },
      { name: 'Border Width/md', type: 'FLOAT', values: { '0': 'Scale/2' } },
      { name: 'Border Width/lg', type: 'FLOAT', values: { '0': 'Scale/4' } },
    ],
  },
  {
    name: 'Mapped',
    modes: { '0': 'Mode 1' },
    variables: [
      { name: 'border/default', type: 'COLOR', values: { '0': 'Neutral/100' } },
      { name: 'border/default light', type: 'COLOR', values: { '0': 'Neutral/75' } },
      { name: 'border/white', type: 'COLOR', values: { '0': 'Neutral/White' } },
      { name: 'border/negative', type: 'COLOR', values: { '0': 'Blue/900' } },
      { name: 'border/negative light', type: 'COLOR', values: { '0': 'Grey/700' } },
      { name: 'border/dark', type: 'COLOR', values: { '0': 'Grey/900' } },
      { name: 'border/success', type: 'COLOR', values: { '0': 'Success/100' } },
      { name: 'border/information', type: 'COLOR', values: { '0': 'Information/100' } },
      { name: 'border/warning', type: 'COLOR', values: { '0': 'Warning/100' } },
      { name: 'border/danger', type: 'COLOR', values: { '0': 'Danger/default' } },
      { name: 'border/action', type: 'COLOR', values: { '0': 'Primary/Default' } },
      { name: 'border/Dynamic', type: 'COLOR', values: { '0': 'Purple/200' } },
      { name: 'border/Dynamic dark', type: 'COLOR', values: { '0': 'Purple/600' } },
      { name: 'border/action neutral', type: 'COLOR', values: { '0': 'Grey/200' } },
      { name: 'border/action-hover', type: 'COLOR', values: { '0': 'Primary/600' } },
      { name: 'border/action AI', type: 'COLOR', values: { '0': 'AI/Default' } },
      { name: 'border/action AI hover', type: 'COLOR', values: { '0': 'AI/500' } },
      { name: 'border/action accent', type: 'COLOR', values: { '0': 'Accent/Default' } },
      { name: 'border/action accent :hover', type: 'COLOR', values: { '0': 'Accent/500' } },
      { name: 'border/focus', type: 'COLOR', values: { '0': 'Primary/Default' } },
      { name: 'border/light action', type: 'COLOR', values: { '0': 'Primary/50' } },
      { name: 'border/light action-hover', type: 'COLOR', values: { '0': 'Primary/100' } },
      { name: 'Surface/page', type: 'COLOR', values: { '0': 'Primary/900' } },
      { name: 'Surface/field', type: 'COLOR', values: { '0': 'Neutral/10' } },
      { name: 'Surface/field-negative', type: 'COLOR', values: { '0': 'Neutral/White' } },
      { name: 'Surface/default', type: 'COLOR', values: { '0': 'Neutral/White' } },
      { name: 'Surface/default bis', type: 'COLOR', values: { '0': 'Neutral/60' } },
      { name: 'Surface/neutral-Hover', type: 'COLOR', values: { '0': 'Neutral/60' } },
      { name: 'Surface/action', type: 'COLOR', values: { '0': 'Primary/Default' } },
      { name: 'Surface/dynamic', type: 'COLOR', values: { '0': 'Purple/50' } },
      { name: 'Surface/action-hover', type: 'COLOR', values: { '0': 'Primary/600' } },
      { name: 'Surface/active', type: 'COLOR', values: { '0': 'Primary/400' } },
      { name: 'Surface/light-accent', type: 'COLOR', values: { '0': 'Accent/50' } },
      { name: 'Surface/light-accent-hover', type: 'COLOR', values: { '0': 'Accent/100' } },
      { name: 'Surface/Accent', type: 'COLOR', values: { '0': 'Accent/Default' } },
      { name: 'Surface/Accent-hover', type: 'COLOR', values: { '0': 'Accent/500' } },
      { name: 'Surface/light-action', type: 'COLOR', values: { '0': 'Primary/50' } },
      { name: 'Surface/light-action-hover', type: 'COLOR', values: { '0': 'Primary/100' } },
      { name: 'Surface/success', type: 'COLOR', values: { '0': 'Success/50' } },
      { name: 'Surface/warning', type: 'COLOR', values: { '0': 'Warning/50' } },
      { name: 'Surface/Information', type: 'COLOR', values: { '0': 'Primary/50' } },
      { name: 'Surface/danger', type: 'COLOR', values: { '0': 'Danger/50' } },
      { name: 'Surface/danger-hover', type: 'COLOR', values: { '0': 'Danger/100' } },
      { name: 'Surface/unselected', type: 'COLOR', values: { '0': 'Neutral/200' } },
      { name: 'Surface/unselected-hover', type: 'COLOR', values: { '0': 'Neutral/300' } },
      { name: 'Surface/AI-gradient-1', type: 'COLOR', values: { '0': 'AI/300' } },
      { name: 'Surface/AI-gradient-2', type: 'COLOR', values: { '0': 'AI/500' } },
      { name: 'Surface/AI-light', type: 'COLOR', values: { '0': 'AI/50' } },
      { name: 'Surface/Orange-gradient-1', type: 'COLOR', values: { '0': 'Accent/300' } },
      { name: 'Surface/Orange-gradient-2', type: 'COLOR', values: { '0': 'Accent/Default' } },
      { name: 'Text/heandings', type: 'COLOR', values: { '0': 'Neutral/Black' } },
      { name: 'Text/body', type: 'COLOR', values: { '0': 'Neutral/900' } },
      { name: 'Text/body secondary', type: 'COLOR', values: { '0': 'Neutral/700' } },
      { name: 'Text/placeholder', type: 'COLOR', values: { '0': 'Neutral/600' } },
      { name: 'Text/placeholder-negative', type: 'COLOR', values: { '0': 'Neutral/600' } },
      { name: 'Text/action', type: 'COLOR', values: { '0': 'Primary/Default' } },
      { name: 'Text/dynamic', type: 'COLOR', values: { '0': 'Purple/600' } },
      { name: 'Text/action AI', type: 'COLOR', values: { '0': 'AI/Default' } },
      { name: 'Text/action AI hover', type: 'COLOR', values: { '0': 'AI/500' } },
      { name: 'Text/on-action', type: 'COLOR', values: { '0': 'Neutral/White' } },
      { name: 'Text/action-hover', type: 'COLOR', values: { '0': 'Primary/600' } },
      { name: 'Text/Information', type: 'COLOR', values: { '0': 'Information/Default' } },
      { name: 'Text/warning', type: 'COLOR', values: { '0': 'Warning/default' } },
      { name: 'Text/success', type: 'COLOR', values: { '0': 'Success/Default' } },
      { name: 'Text/danger', type: 'COLOR', values: { '0': 'Danger/default' } },
      { name: 'Text/Accent', type: 'COLOR', values: { '0': 'Accent/Default' } },
      { name: 'Icon/title', type: 'COLOR', values: { '0': 'Neutral/Black' } },
      { name: 'Icon/default', type: 'COLOR', values: { '0': 'Neutral/900' } },
      { name: 'Icon/secondary', type: 'COLOR', values: { '0': 'Neutral/700' } },
      { name: 'Icon/action', type: 'COLOR', values: { '0': 'Primary/Default' } },
      { name: 'Icon/dynamic', type: 'COLOR', values: { '0': 'Purple/600' } },
      { name: 'Icon/action-hover', type: 'COLOR', values: { '0': 'Primary/600' } },
      { name: 'Icon/Accent', type: 'COLOR', values: { '0': 'Accent/Default' } },
      { name: 'Icon/Accent hover', type: 'COLOR', values: { '0': 'Accent/500' } },
      { name: 'Icon/action-AI', type: 'COLOR', values: { '0': 'AI/Default' } },
      { name: 'Icon/action-AI hover', type: 'COLOR', values: { '0': 'AI/500' } },
      { name: 'Icon/on-action', type: 'COLOR', values: { '0': 'Neutral/White' } },
      { name: 'Icon/Information', type: 'COLOR', values: { '0': 'Information/Default' } },
      { name: 'Icon/warning', type: 'COLOR', values: { '0': 'Warning/default' } },
      { name: 'Icon/success', type: 'COLOR', values: { '0': 'Success/Default' } },
      { name: 'Icon/danger', type: 'COLOR', values: { '0': 'Danger/default' } },
      { name: 'Context/Grey/Light', type: 'COLOR', values: { '0': 'Grey/50' } },
      { name: 'Context/Grey/dark', type: 'COLOR', values: { '0': 'Grey/600' } },
      { name: 'Context/Blue/lighter', type: 'COLOR', values: { '0': 'Primary/50' } },
      { name: 'Context/Blue/light', type: 'COLOR', values: { '0': 'Primary/200' } },
      { name: 'Context/Blue/Default', type: 'COLOR', values: { '0': 'Primary/300' } },
      { name: 'Context/Blue/dark', type: 'COLOR', values: { '0': 'Primary/400' } },
      { name: 'Context/Blue/darker', type: 'COLOR', values: { '0': 'Primary/600' } },
      { name: 'Context/Red/lighter', type: 'COLOR', values: { '0': 'Danger/50' } },
      { name: 'Context/Red/light', type: 'COLOR', values: { '0': 'Danger/200' } },
      { name: 'Context/Red/Default', type: 'COLOR', values: { '0': 'Danger/300' } },
      { name: 'Context/Red/dark', type: 'COLOR', values: { '0': 'Danger/400' } },
      { name: 'Context/Red/darker', type: 'COLOR', values: { '0': 'Danger/600' } },
      { name: 'Context/Green/lighter', type: 'COLOR', values: { '0': 'Green/50' } },
      { name: 'Context/Green/light', type: 'COLOR', values: { '0': 'Green/200' } },
      { name: 'Context/Green/Default', type: 'COLOR', values: { '0': 'Green/300' } },
      { name: 'Context/Green/dark', type: 'COLOR', values: { '0': 'Green/400' } },
      { name: 'Context/Green/darker', type: 'COLOR', values: { '0': 'Green/600' } },
      { name: 'Context/Purple/lighter', type: 'COLOR', values: { '0': 'Purple/50' } },
      { name: 'Context/Purple/light', type: 'COLOR', values: { '0': 'Purple/200' } },
      { name: 'Context/Purple/Default', type: 'COLOR', values: { '0': 'Purple/300' } },
      { name: 'Context/Purple/dark', type: 'COLOR', values: { '0': 'Purple/400' } },
      { name: 'Context/Purple/darker', type: 'COLOR', values: { '0': 'Purple/600' } },
      { name: 'Context/Orange/lighter', type: 'COLOR', values: { '0': 'Orange/50' } },
      { name: 'Context/Orange/light', type: 'COLOR', values: { '0': 'Orange/200' } },
      { name: 'Context/Orange/Default', type: 'COLOR', values: { '0': 'Orange/300' } },
      { name: 'Context/Orange/dark', type: 'COLOR', values: { '0': 'Orange/400' } },
      { name: 'Context/Orange/darker', type: 'COLOR', values: { '0': 'Orange/600' } },
      { name: 'Glow/primary', type: 'COLOR', values: { '0': 'Primary/200' } },
      { name: 'Glow/IA', type: 'COLOR', values: { '0': 'AI/200' } },
      { name: 'Glow/Accent', type: 'COLOR', values: { '0': 'Accent/200' } },
      { name: 'Glow/Error', type: 'COLOR', values: { '0': 'Danger/200' } },
      { name: 'Glow/Tertiary', type: 'COLOR', values: { '0': 'Grey/200' } },
    ],
  },
  {
    name: 'Responsive',
    modes: { '0': 'Desktop', '1': 'Mobile' },
    variables: [
      { name: 'h1/font size', type: 'FLOAT', values: { '0': 40, '1': 30 } },
      { name: 'h1/line height', type: 'FLOAT', values: { '0': 50, '1': 40 } },
      { name: 'h1/paragraph spacing', type: 'FLOAT', values: { '0': 12, '1': 12 } },
      { name: 'h2/font size', type: 'FLOAT', values: { '0': 20, '1': 14 } },
      { name: 'h2/line height', type: 'FLOAT', values: { '0': 24, '1': 24 } },
      { name: 'h2/paragraph spacing', type: 'FLOAT', values: { '0': 8, '1': 8 } },
      { name: 'h3/font size', type: 'FLOAT', values: { '0': 16, '1': 12 } },
      { name: 'h3/line height', type: 'FLOAT', values: { '0': 20, '1': 20 } },
      { name: 'h3/paragraph spacing', type: 'FLOAT', values: { '0': 8, '1': 8 } },
      { name: 'h4/font size', type: 'FLOAT', values: { '0': 14, '1': 12 } },
      { name: 'h4/line height', type: 'FLOAT', values: { '0': 20, '1': 20 } },
      { name: 'h4/paragraph spacing', type: 'FLOAT', values: { '0': 8, '1': 8 } },
      { name: 'body/font size', type: 'FLOAT', values: { '0': 14, '1': 12 } },
      { name: 'body/line height', type: 'FLOAT', values: { '0': 20, '1': 20 } },
      { name: 'body/paragraph spacing', type: 'FLOAT', values: { '0': 8, '1': 8 } },
      { name: 'body small/font size', type: 'FLOAT', values: { '0': 12, '1': 12 } },
      { name: 'body small/line height', type: 'FLOAT', values: { '0': 12, '1': 18 } },
      { name: 'body small/paragraph spacing', type: 'FLOAT', values: { '0': 8, '1': 8 } },
      { name: 'caption/font size', type: 'FLOAT', values: { '0': 10, '1': 10 } },
      { name: 'caption/line height', type: 'FLOAT', values: { '0': 16, '1': 16 } },
      { name: 'caption/paragraph spacing', type: 'FLOAT', values: { '0': 4, '1': 8 } },
      { name: 'Mentions/font size', type: 'FLOAT', values: { '0': 8, '1': 8 } },
      { name: 'Mentions/line height', type: 'FLOAT', values: { '0': 4, '1': 8 } },
      { name: 'Mentions/paragraph spacing', type: 'FLOAT', values: { '0': 8, '1': 8 } },
      { name: 'Device Size', type: 'FLOAT', values: { '0': 1440, '1': 440 } },
      { name: 'spacing/none', type: 'FLOAT', values: { '0': 'Scale/0', '1': 'Scale/0' } },
      { name: 'spacing/xs', type: 'FLOAT', values: { '0': 'Scale/2', '1': 'Scale/2' } },
      { name: 'spacing/sm', type: 'FLOAT', values: { '0': 'Scale/4', '1': 'Scale/4' } },
      { name: 'spacing/md', type: 'FLOAT', values: { '0': 'Scale/8', '1': 'Scale/6' } },
      { name: 'spacing/lg', type: 'FLOAT', values: { '0': 'Scale/12', '1': 'Scale/8' } },
      { name: 'spacing/xl', type: 'FLOAT', values: { '0': 'Scale/16', '1': 'Scale/12' } },
      { name: 'spacing/2xl', type: 'FLOAT', values: { '0': 'Scale/20', '1': 'Scale/16' } },
      { name: 'spacing/3xl', type: 'FLOAT', values: { '0': 'Scale/24', '1': 'Scale/20' } },
      { name: 'spacing/4xl', type: 'FLOAT', values: { '0': 'Scale/32', '1': 'Scale/24' } },
      { name: 'radius/none', type: 'FLOAT', values: { '0': 'Scale/0', '1': 'Scale/0' } },
      { name: 'radius/sm', type: 'FLOAT', values: { '0': 'Scale/4', '1': 'Scale/4' } },
      { name: 'radius/md', type: 'FLOAT', values: { '0': 'Scale/6', '1': 'Scale/6' } },
      { name: 'radius/lg', type: 'FLOAT', values: { '0': 'Scale/8', '1': 'Scale/6' } },
      { name: 'radius/xl', type: 'FLOAT', values: { '0': 'Scale/12', '1': 'Scale/8' } },
      { name: 'radius/full', type: 'FLOAT', values: { '0': 'Scale/100', '1': 'Scale/100' } },
      { name: 'sizing/icon-xxxs', type: 'FLOAT', values: { '0': 10, '1': 10 } },
      { name: 'sizing/icon-xxs', type: 'FLOAT', values: { '0': 14, '1': 14 } },
      { name: 'sizing/icon-xs', type: 'FLOAT', values: { '0': 18, '1': 18 } },
      { name: 'sizing/icon-default', type: 'FLOAT', values: { '0': 'Scale/20', '1': 'Scale/20' } },
      { name: 'sizing/icon-xl', type: 'FLOAT', values: { '0': 48, '1': 48 } },
      { name: 'sizing/sm', type: 'FLOAT', values: { '0': 'Scale/16', '1': 'Scale/16' } },
      { name: 'sizing/md', type: 'FLOAT', values: { '0': 'Scale/20', '1': 'Scale/20' } },
      { name: 'sizing/lg', type: 'FLOAT', values: { '0': 'Scale/24', '1': 'Scale/24' } },
      { name: 'sizing/xl', type: 'FLOAT', values: { '0': 'Scale/32', '1': 'Scale/32' } },
      { name: 'opacity/disabled', type: 'FLOAT', values: { '0': 'Opacity/50', '1': 'Opacity/50' } },
    ],
  },
];
